// <auto-generated />
using Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405113402_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Database.Entities.BodyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_body_parts");

                    b.ToTable("body_parts", (string)null);
                });

            modelBuilder.Entity("Core.Database.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("Core.Database.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("BodyPartId")
                        .HasColumnType("integer")
                        .HasColumnName("body_part_id");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("TargetMuscleId")
                        .HasColumnType("integer")
                        .HasColumnName("target_muscle_id");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("BodyPartId")
                        .HasDatabaseName("ix_exercises_body_part_id");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_exercises_equipment_id");

                    b.HasIndex("TargetMuscleId")
                        .HasDatabaseName("ix_exercises_target_muscle_id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("Core.Database.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyPartId")
                        .HasColumnType("integer")
                        .HasColumnName("body_part_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_muscles");

                    b.HasIndex("BodyPartId")
                        .HasDatabaseName("ix_muscles_body_part_id");

                    b.ToTable("muscles", (string)null);
                });

            modelBuilder.Entity("ExerciseSecondaryMuscle", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("character varying(36)")
                        .HasColumnName("exercise_id");

                    b.Property<int>("SecondaryMuscleId")
                        .HasColumnType("integer")
                        .HasColumnName("secondary_muscle_id");

                    b.HasKey("ExerciseId", "SecondaryMuscleId")
                        .HasName("pk_exercise_secondary_muscle");

                    b.HasIndex("SecondaryMuscleId")
                        .HasDatabaseName("ix_exercise_secondary_muscle_secondary_muscle_id");

                    b.ToTable("exercise_secondary_muscle", (string)null);
                });

            modelBuilder.Entity("Core.Database.Entities.Exercise", b =>
                {
                    b.HasOne("Core.Database.Entities.BodyPart", "BodyPart")
                        .WithMany("Exercises")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_body_parts_body_part_id");

                    b.HasOne("Core.Database.Entities.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_equipment_equipment_id");

                    b.HasOne("Core.Database.Entities.Muscle", "Target")
                        .WithMany("Exercises")
                        .HasForeignKey("TargetMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_muscles_target_muscle_id");

                    b.Navigation("BodyPart");

                    b.Navigation("Equipment");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Core.Database.Entities.Muscle", b =>
                {
                    b.HasOne("Core.Database.Entities.BodyPart", "BodyPart")
                        .WithMany("Muscles")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_muscles_body_parts_body_part_id");

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("ExerciseSecondaryMuscle", b =>
                {
                    b.HasOne("Core.Database.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_secondary_muscle_exercises_exercise_id");

                    b.HasOne("Core.Database.Entities.Muscle", null)
                        .WithMany()
                        .HasForeignKey("SecondaryMuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_secondary_muscle_muscles_secondary_muscle_id");
                });

            modelBuilder.Entity("Core.Database.Entities.BodyPart", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("Core.Database.Entities.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Core.Database.Entities.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
